### ISSUE TITLE
BGP lab (Option 23) doesn't properly apply host1 and host2 configs

### ISSUE THREAD

**Issue by DimitriCapetz** [aristanetworks/atd-public#102]
When executing the BGP lab, host1 and host2 become inaccessible and can no longer communicate with CVP.  The Tasks that get generated in CVP never complete.

The nodes can still be reached via their "in-band" interface from the leaves. For example, from leaf1...

ssh -l arista 172.16.115.100

drops you into host1.  The config seems correct from first glance, but CVP is not pingable via the Ma1 interface.  I can look into the config more when I'm back at home this afternoon.

**Comment by networkRob** [comment]
Fixed in #96
