### ISSUE TITLE
ntp not configured on leafs

### ISSUE THREAD

**Issue by edgarshine** [aristanetworks/atd-public#120]
**Describe the bug**
NTP is not configured when choosing "cvp" or "27" in Jumphost.
The effect is when we go to CVP Telemetry we'll see "red" flags recommending to have it configured.

**To Reproduce**
Fresh start, go to Jumphost, select "cvp". Log in any leaf switch and run:
leaf1#show run | grep ntp
leaf1#

**Expected behavior**
Better described as "desired behavior".
NTP configured and no error messaged displayed in CVP telemetry.

**Screenshots**
<img width="1034" alt="Captura de Tela 2020-01-30 às 01 15 49" src="https://user-images.githubusercontent.com/18684772/73419515-264e1800-42fe-11ea-9dd2-b8c49b9ef692.png">

**Additional context**
No additional comments.

**Comment by networkRob** [comment]
ntp is now configured in testdrive
