### ISSUE TITLE
Lab Guide Syntax Updates - Remove Deprecated Commands

### ISSUE THREAD

**Issue by coreyhines** [aristanetworks/atd-public#124]
**Describe the bug**
A clear and concise description of what the bug is. Please include the lab module if applicable.
cvx.html labguide contains error in syntax for setting lacp timer

**To Reproduce**
Steps to reproduce the behavior.
leaf3(config-if-Et4)#lacp rate fast
% Unavailable command (This command is deprecated by 'lacp timer')
leaf3(config-if-Et4)#lacp timer ?
  fast    1 second whether synchronized or not
  normal  30 seconds while synchronized, 1 second while synchronizing

leaf3(config-if-Et4)#lacp timer fast

**Expected behavior**
labguide update

interface Ethernet4
  description HOST2
  channel-group 4 mode active
  lacp **timer** fast
**Screenshots**
![image](https://user-images.githubusercontent.com/8289837/73487792-554fa280-436d-11ea-86ae-bb942786afce.png)

**Additional context**

**Comment by DimitriCapetz** [comment]
Can we expand the scope of this?  The same syntax issue is in the L2EVPN lab as well.

**Comment by DimitriCapetz** [comment]
I'm just going to expand the scope to fix all deprecated commands I find :)
