### ISSUE TITLE
Move Common Configs to ATD-INFRA Configlet for Datacenter-latest

### ISSUE THREAD

**Issue by DimitriCapetz** [aristanetworks/atd-public#135]
**Describe the bug**
There are some pieces of config (DNS, API) that can be better served in the ATD-INFRA configlet.  This is already in process for the RATD.

**To Reproduce**
Just look at the configlets :)

**Expected behavior**
Configlets should follow Arista best-practice structure on re-use where possible.

**Comment by networkRob** [comment]
Need to double check this in testdrive

**Comment by DimitriCapetz** [comment]
Fixed via above PRs
