### ISSUE TITLE
Add Static SR-TE Policies to RATD

### ISSUE THREAD

**Issue by DimitriCapetz** [aristanetworks/atd-public#143]
**Is your feature request related to a problem? Please describe.**
No problem, just to demonstrate new capabilities.

**Describe the solution you'd like**
We should be able to demonstrate and configure static SR-TE policies for path manipulation in the RATD topology.  This is a key feature for ISIS-SR and customers would like to see it in action.

**Describe alternatives you've considered**
Not having it is not an option!

**Additional context**
Nada

**Comment by networkRob** [comment]
@DimitriCapetz has this been implemented?

**Comment by networkRob** [comment]
This has been implemented.
