### ISSUE TITLE
CLI Type in labguides for BFD

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#144]
In the datacenter-latest topo, the l3ls lab, there is a type referencing the old CLI syntax for BFD in BGP. 
```
configure
router bgp 65002
  neighbor <neighbor_ip> fall-over bfd
```

Should read:
```
neighbor <neighbor_ip> bfd
```

**Comment by DimitriCapetz** [comment]
Fixed in cvp-green-release branch.  Will be pulled into master with other changes.
