### ISSUE TITLE
Fix Advanced routing for Media Engineer lab

### ISSUE THREAD

**Issue by RyanM-Arista** [aristanetworks/atd-public#145]
Current issue is that the multicast streams are not being observed in the ATD topology as was the case in previous Datacenter topology.  

Observed that the multicast streams are taking the incorrect gateway/interface when starting up iperf script. 

Solution:
add static routes via bash to send the multicast streams to the correct gateway on each host.  

host1
sudo ip route add 239.103.1.1/32 dev et1
sudo ip route add 239.103.1.2/32 dev et1
sudo ip route add 239.103.1.3/32 dev et1

host2
sudo ip route add 239.103.1.1/32 dev et2
sudo ip route add 239.103.1.2/32 dev et2
sudo ip route add 239.103.1.3/32 dev et2

**Comment by networkRob** [comment]
Why don't we just add those static routes in EOS on the host nodes?

**Comment by networkRob** [comment]
@RyanM-Arista what you're proposing works, I think it would be best to add those commands into the actual `mcast-receiver.sh` / `mcast-sender.sh` bash scripts.  Just add them in the beginning before the loops and iperf commands.

**Comment by RyanM-Arista** [comment]
Pull request #146 has been submitted for review

**Comment by networkRob** [comment]
Closed via #146
