### ISSUE TITLE
Guacamole - Routing ATD

### ISSUE THREAD

**Issue by brokenpackets** [aristanetworks/atd-public#147]
**Describe the bug**
Guacamole is displaying the hosts for the regular DC ATD, and not the full Routing ATD topology. Not usually required in networks with outbound SSH access, but some customers restrict this, and a multi-tab Guacamole view is the easiest way around this.

**Expected behavior**
This should show the ATD-specific hosts.

**Screenshots**
![image](https://user-images.githubusercontent.com/36974147/76457217-9a67eb00-6395-11ea-84bd-38cdd1eb9d77.png)

**Comment by networkRob** [comment]
Fix is in PR #55

**Comment by networkRob** [comment]
Just needs to be reviewed/tested again for any topo changes we have made recently.

**Comment by networkRob** [comment]
Fixed in #159
