### ISSUE TITLE
Update labguides for CVP 2020.1.0

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#155]
The following items need to be updated before updating CVP to 2020.1.0 in the ATDs.

- Need to update any labguides for `Datacenter-Latest` and `Beta-Datacenter` topologies for the CVP 2020.1.0 release.
- Need to update the labguides for the updated arista user password.

**Comment by DimitriCapetz** [comment]
CVP Configlet and CVP Change Control/Telemetry labs have been updated with new workflows and screenshots.  Changes pushed to cvp-green-release branch.

**Comment by networkRob** [comment]
Fixed in #159
