### ISSUE TITLE
Error message if click "Start" when system is already started.

### ISSUE THREAD

**Issue by edgarshine** [aristanetworks/atd-public#156]
**Describe the bug**
Landing page. All devices running. When clicking "start" a error page is displayed.

**To Reproduce**
Start topology, wait for all devices running. Click Start again.

**Expected behavior**
I'd expect a nice message "Already started" instead of an error page.

**Screenshots**
<img width="1021" alt="Captura de Tela 2020-05-12 às 13 01 57" src="https://user-images.githubusercontent.com/18684772/81717387-ddefdb80-9450-11ea-89de-40245b7586b8.png">

**Additional context**
Beta ATD Green

**Comment by networkRob** [comment]
Closing this as we are on testdrive platform.
