### ISSUE TITLE
Log messages regarding interface Management1

### ISSUE THREAD

**Issue by edgarshine** [aristanetworks/atd-public#157]
**Describe the bug**
Log messages:
May 14 02:34:12 leaf1 PhyEthtool: %ETH-4-POLLLINKSTATUSFAIL: Failed to poll link status on interface Management1 ([Errno 95] Operation not supported) (message repeated 304 times in 600.162 secs)
May 14 02:36:20 leaf1 PhyEthtool: %ETH-4-SETLINKMODEFAIL: Failed to set speed/duplex on interface Management1 to auto/auto ([Errno 95] Operation not supported) (message repeated 2 times in 360.096 secs)
May 14 02:36:20 leaf1 PhyEthtool: %ETH-4-SETPAUSEPARAMFAIL: Failed to set pause parameters on interface Management1 ([Errno 95] Operation not supported) (message repeated 2 times in 360.096 secs)

**To Reproduce**
No special requirements

**Expected behavior**
No log messages.

**Screenshots**

**Additional context**
Beta GREEN

**Comment by networkRob** [comment]
Closing this as we are on testdrive platform.
