### ISSUE TITLE
L3EVPN Lab Host1 and Leaf1 connections failure

### ISSUE THREAD

**Issue by edgarshine** [aristanetworks/atd-public#158]
**Describe the bug**
Not connection between Host1 and Leaf1 on network 172.16.115.0/24
Initial findings points to Leaf1 provisioning inconsistency.

**To Reproduce**
Found in step 7-2 first test trail.
Apparently this happens if you go straight to L3EVPN lab after a fresh topology start.
Doing a reset in the Jumphost and applying l3evpn profile again fixed the lab.

**Expected behavior**
Successful ping in step 7-2 L3EVPN Lab doc

**Screenshots**
host1#sh ip int br
                                                                                         Address
Interface           IP Address              Status       Protocol                 MTU    Owner
------------------- ----------------------- ------------ -------------------- ---------- -------
Management1         192.168.0.31/24         up           up                      1500
Port-Channel1       172.16.112.201/24       up           up                      1500
Port-Channel2       172.16.115.100/24       down         lowerlayerdown          1500

host1#sh lldp ne
Last table change time   : 1:00:33 ago
Number of table inserts  : 1
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et1           leaf1.arista.lab         Ethernet4           120

host1#sh run int e3
interface Ethernet3
   channel-group 2 mode active
   lacp timer fast
host1#sh run int po2
interface Port-Channel2
   no switchport
   ip address 172.16.115.100/24
host1#sh int po2
Port-Channel2 is down, line protocol is lowerlayerdown (notconnect)
  Hardware is Port-Channel, address is 0415.d408.7e6c
  Internet address is 172.16.115.100/24
  Broadcast address is 255.255.255.255
  IP MTU 1500 bytes (default)
  Full-duplex, Unconfigured
  Active members in this channel: 0
  Fallback mode is: off
  Down 1 hour, 2 minutes, 21 seconds
  1 link status changes since last clear
  Last clearing of "show interface" counters never
  5 minutes input rate 0 bps (- with framing overhead), 0 packets/sec
  5 minutes output rate 0 bps (- with framing overhead), 0 packets/sec
     0 packets input, 0 bytes
     Received 0 broadcasts, 0 multicast
     0 input errors, 0 input discards
     0 packets output, 0 bytes
     Sent 0 broadcasts, 0 multicast
     0 output errors, 0 output discards
host1#sh int e3
Ethernet3 is up, line protocol is up (connected)
  Hardware is Ethernet, address is 32a6.e203.17b6 (bia 32a6.e203.17b6)
  Member of Port-Channel2
  Ethernet MTU 9214 bytes
  Full-duplex, Unconfigured, auto negotiation: off, uni-link: n/a
  Up 1 hour, 2 minutes, 53 seconds
  Loopback Mode : None
  2 link status changes since last clear
  Last clearing of "show interface" counters never
  5 minutes input rate 0 bps (- with framing overhead), 0 packets/sec
  5 minutes output rate 0 bps (- with framing overhead), 0 packets/sec
     0 packets input, 0 bytes
     Received 0 broadcasts, 0 multicast
     0 runts, 0 giants
     0 input errors, 0 CRC, 0 alignment, 0 symbol, 0 input discards
     0 PAUSE input
     3901 packets output, 497006 bytes
     Sent 0 broadcasts, 3901 multicast
     0 output errors, 0 collisions
     0 late collision, 0 deferred, 0 output discards
     0 PAUSE output
host1#sh port-channel 2
Port Channel Port-Channel2:
  No Active Ports
  Configured, but inactive ports:
       Port         Reason unconfigured
    --------------- -----------------------------------------
       Ethernet3    waiting for LACP response
       Ethernet4    link down while waiting for LACP response

leaf1#sh lldp ne
Last table change time   : 1:03:43 ago
Number of table inserts  : 3
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et2           spine1.arista.lab        Ethernet2           120
Et3           spine2.arista.lab        Ethernet2           120
Et4           host1.arista.lab         Ethernet1           120
leaf1#sh ip int br
                                                                                 Address
Interface         IP Address             Status       Protocol            MTU    Owner
----------------- ---------------------- ------------ -------------- ----------- -------
Ethernet2         172.16.200.2/30        up           up                 1500
Ethernet3         172.16.200.18/30       up           up                 1500
Loopback0         172.16.0.3/32          up           up                65535
Loopback1         1.1.1.1/32             up           up                65535
Management1       192.168.0.14/24        up           up                 1500
Vlan12            172.16.112.1/24        up           up                 1500
Vlan4094          unassigned             up           up                 9164

! Command: show running-config
! device: leaf1 (vEOS, EOS-4.24.0F)
!
! boot system flash:/CloudEOS.swi
!
daemon TerminAttr
   exec /usr/bin/TerminAttr -ingestgrpcurl=192.168.0.5:9910 -taillogs -ingestauth=key,1a38fe7df56879d685e51b6f0ff86327 -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent
   no shutdown
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname leaf1
dns domain arista.lab
!
spanning-tree mode mstp
!
tacacs-server key 7 070E33455D1D18
tacacs-server host 192.168.0.4
!
aaa authorization exec default local
!
no aaa root
!
username admin privilege 15 role network-admin secret 5 $1$5O85YVVn$HrXcfOivJEnISTMb6xrJc.
username arista privilege 15 role network-admin secret sha512 $6$l1fenP3qXMDvIZKX$6/esgH2r8x8GbV6lQX7svakkKSz3ku3MsGVkftyhJ7Jv5I/BZ52pyZr8WIM6JvO6JYfpbb8MQ8ax8DxHm7Xvg0
username arista ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6bJB3TkBEQZ9jNyO1kbdU0P20gZ1D72CvsPNZ5S4bbciBNTT/MHX8GwyLmM9k+ihaHK2JtRhWFcdsm9MojRgjAuzw4wn/6pa92y/93GvaYL//dOBXrHctZsX3PX7TZFL9VVBVA8aFp5iXxEM8uyKWhxnBo/D0eR25Jed4gHVHQMi6Hyh7eKRpE3E6kvRlSkhNikZ5EwdoM7lg2i6rjf7+o3G6isGtxliMZD98N6qWW79U6euS07
2qkK/q3dfgyHdd8a8MD5VLWbYR9ikhKwpXAmxcFn5aRllqXJ++QAW0NO78noI91ICRxpAuQSzgrntdwXdyFWiqyiD3AxK28qWZ arista@labaccess
!
vlan 12,34
!
interface Port-Channel4
   switchport access vlan 12
!
interface Ethernet1
   shutdown
!
interface Ethernet2
   no switchport
   ip address 172.16.200.2/30
!
interface Ethernet3
   no switchport
   ip address 172.16.200.18/30
!
interface Ethernet4
   channel-group 4 mode active
   lacp timer fast
!
interface Ethernet5
   shutdown
!
interface Ethernet6
!
interface Ethernet7
!
interface Ethernet8
!
interface Ethernet9
!
interface Ethernet10
!
interface Ethernet11
!
interface Ethernet12
!
interface Ethernet13
!
interface Ethernet14
!
interface Ethernet15
!
interface Ethernet16
!
interface Ethernet17
!
interface Ethernet18
!
interface Ethernet19
!
interface Ethernet20
!
interface Ethernet21
!
interface Ethernet22
!
interface Ethernet23
!
interface Ethernet24
!
interface Ethernet25
!
interface Ethernet26
!
interface Ethernet27
!
interface Ethernet28
!
interface Ethernet29
!
interface Ethernet30
!
interface Ethernet31
!
interface Ethernet32
!
interface Loopback0
   ip address 172.16.0.3/32
!
interface Loopback1
   ip address 1.1.1.1/32
   ip address 99.99.99.99/32 secondary
!
interface Management1
   ip address 192.168.0.14/24
   no lldp transmit
   no lldp receive
!
interface Vlan12
   ip address virtual 172.16.112.1/24
!
interface Vxlan1
   vxlan source-interface Loopback1
   vxlan udp-port 4789
   vxlan vlan 12 vni 1200
!
event-handler iptables-vxlan
   trigger on-boot
   action bash sudo iptables -I INPUT 1 -p udp --dport 4789 -j ACCEPT
   asynchronous
!
event-handler ovs-restart
   trigger on-boot
   action bash sudo systemctl restart openvswitch
   delay 30
   asynchronous
!
ip routing
!
router bgp 65101
   router-id 172.16.0.3
   maximum-paths 2 ecmp 2
   neighbor SPINE peer group
   neighbor SPINE remote-as 65001
   neighbor SPINE bfd
   neighbor SPINE maximum-routes 12000
   neighbor SPINE-EVPN-TRANSIT peer group
   neighbor SPINE-EVPN-TRANSIT remote-as 65001
   neighbor SPINE-EVPN-TRANSIT next-hop-unchanged
   neighbor SPINE-EVPN-TRANSIT update-source Loopback0
   neighbor SPINE-EVPN-TRANSIT ebgp-multihop
   neighbor SPINE-EVPN-TRANSIT send-community extended
   neighbor SPINE-EVPN-TRANSIT maximum-routes 0
   neighbor 172.16.0.1 peer group SPINE-EVPN-TRANSIT
   neighbor 172.16.0.2 peer group SPINE-EVPN-TRANSIT
   neighbor 172.16.200.1 peer group SPINE
   neighbor 172.16.200.17 peer group SPINE
   redistribute connected
   neighbor SPINE peer group
   neighbor SPINE remote-as 65001
   neighbor SPINE bfd
   neighbor SPINE maximum-routes 12000
   neighbor SPINE-EVPN-TRANSIT peer group
   neighbor SPINE-EVPN-TRANSIT remote-as 65001
   neighbor SPINE-EVPN-TRANSIT next-hop-unchanged
   neighbor SPINE-EVPN-TRANSIT update-source Loopback0
   neighbor SPINE-EVPN-TRANSIT ebgp-multihop
   neighbor SPINE-EVPN-TRANSIT send-community extended
   neighbor SPINE-EVPN-TRANSIT maximum-routes 0
   neighbor 172.16.0.1 peer group SPINE-EVPN-TRANSIT
   neighbor 172.16.0.2 peer group SPINE-EVPN-TRANSIT
   neighbor 172.16.200.1 peer group SPINE
   neighbor 172.16.200.17 peer group SPINE
   redistribute connected
   !
   vlan 12
      rd 1.1.1.1:12
      route-target both 1:12
      redistribute learned
   !
   address-family evpn
      neighbor SPINE-EVPN-TRANSIT activate
   !
   address-family ipv4
      no neighbor SPINE-EVPN-TRANSIT activate
!
management api http-commands
   protocol http
   no shutdown
!
end
##### 

**Additional context**

**Comment by networkRob** [comment]
closing this as we are on testdrive platform. If this is still an issue we can reopen it.
