### ISSUE TITLE
Move Labguides under appropriate topology

### ISSUE THREAD

**Issue by terensapp** [aristanetworks/atd-public#19]
**Describe the bug**
Read the title

**To Reproduce**
Re-read the title

**Expected behavior**
Do what title says

**Comment by networkRob** [comment]
@MitchV85 I'll have you help me out with this one.

**Comment by networkRob** [comment]
@terensapp can you please elaborate?
So I read the title 'Describe the bug', not sure what the bug is.
I re-read the title, this time it changed to 'To Reproduce' (still unclear).
Then I tried to do what the title says, and not sure how to do 'Expected Behavior'.

**Comment by terensapp** [comment]
My apologies, here maybe a screen shot will help:

![image](https://user-images.githubusercontent.com/9464590/57155615-8f215780-6da1-11e9-8cf5-59e8cca75b0f.png)

**Comment by networkRob** [comment]
Thanks! that does help, I'm a visual learner

**Comment by terensapp** [comment]
Here's one more representation if it helps provide a little more clarity: 
![image](https://user-images.githubusercontent.com/9464590/57155985-6a79af80-6da2-11e9-834a-b33887d495eb.png)
