### ISSUE TITLE
Configuration on deployed virtual nodes removed once the configlets updated

### ISSUE THREAD

**Issue by andriirr** [aristanetworks/atd-public#212]
Lets assume we have standard ATD lab deployment (datacenter-latest).
Configuration changes were made to the vEOS nodes using CLI and not CVP configlets.

At some point BaseIPv4_* CVP configlet updated:

```
<collected from the jump host>
...
Sep 11 11:07:44 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    Updated Configlet: tshoot-host1-Tshoot-intro
Sep 11 11:07:45 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    Updated Configlet: Leaf3-VXLAN-Lab
Sep 11 11:07:45 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    Updated Configlet: Leaf3-BGP-Lab
Sep 11 11:07:55 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    Performing check for pending tasks.
Sep 11 11:07:55 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    Pending tasks found, will execute
Sep 11 11:07:57 ip-10-33-4-207 /gitConfigletSync.py[6124]: [INFO]    All pending tasks are executing
```
The gitConfigletSync.py script will form set of CVP tasks to update the BaseIPv4 configlets, overriding configuration that present on vEOS nodes:

<img width="1186" alt="Screenshot 2020-09-15 at 14 16 14" src="https://user-images.githubusercontent.com/58480764/93217575-24d44180-f761-11ea-9d7c-9009f4da6af5.png">

Although it might be expected for CVP-managed topologies, this becomes an issue when configuration is done via CLI. We either fix the behaviour (don't try to re-install configlets for already provisioned topologies) or come up with a separate "non-cvp" topology that will be available via web-interface

**Comment by networkRob** [comment]
This is expected and intended behavior. The reason for this is if we update our configlets or add new ones, we want those imported into cvp. If any of those configlets are already applied to a node, a task is created automatically by cvp. We then want those tasks executed to prevent future issues. 

A non cvp type topology is in the works for testing.

**Comment by andriirr** [comment]
thank you for your reply, Rob
