### ISSUE TITLE
Add public IP to the labguides for ease of use

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#22]
**Is your feature request related to a problem? Please describe.**
In the `connecting.rst` and `programmability_connecting.rst` files, it would be helpful to show the user's public IP for their topo within the labguide for their `ssh` cmds.

**Describe the solution you'd like**
Modify the `atdFiles.sh` script to get current public IP for the topo and to update the string in the above labguides to reflect the IP.

**Describe alternatives you've considered**
Nope

**Additional context**
![image](https://user-images.githubusercontent.com/39608748/57540758-0eb7a500-7313-11e9-9d46-f5e8f35d2615.png)

**Comment by RyanM-Arista** [comment]
in the interim, amended the documentation picture to not show the IP address, this modification is in the broadcast-training branch
