### ISSUE TITLE
Routing: Fix IPAddr on BaseIPV4_EOS3 Eth6.

### ISSUE THREAD

**Issue by brokenpackets** [aristanetworks/atd-public#65]
**Describe the bug**
EOS3 has the following configuration on Eth6. This needs to be adjusted to fit the standard model (this is already fixed in the SVC configlet). 
```
interface Ethernet6
   description EOS20
   no switchport
   ip address 10.3.20.2/24 !! change to 10.3.20.3/24
```

**Comment by DimitriCapetz** [comment]
Fixed as part of PR #133.  Good eye...I never would have noticed that.
