### ISSUE TITLE
Fix IP address on SVI in configlet "Leaf2-VXLAN-Lab"

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/atd-public#68]
SVI for VLAN 12 is incorrect for VLAN 12. Should be 172.16.112.3 and not 172.16.112.4 (which is already assigned to Leaf3).

**Comment by bingbucks** [comment]
I'd assign to myself, but I can't change assignee nor labels.

**Comment by networkRob** [comment]
Fixed in #75
