### ISSUE TITLE
ENHANCEMENT: "cvx01-Controller" not needed in "vxlan" (option 24)

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/atd-public#70]
We *can* remove this from MenuOptions.yaml since it's not needed in the VXLAN lab nor the CVX lab:
![image](https://user-images.githubusercontent.com/4934710/61652980-37e7a080-ac87-11e9-9a3b-32040f8d9ad0.png)

Even though the CVX ATD lab uses "vxlan" (option 24), the beginning of the ATD lab guide for the CVX lab has the user handjam the CLI anyways:
![image](https://user-images.githubusercontent.com/4934710/61652990-403fdb80-ac87-11e9-8a9b-875a800b2556.png)

... which is exactly what the "cvx01-Controller" configlet is anyways:
![image](https://user-images.githubusercontent.com/4934710/61652997-4635bc80-ac87-11e9-8371-8f6632d46332.png)

**Comment by bingbucks** [comment]
Assign to me please.

**Comment by networkRob** [comment]
Fixed in #75
