### ISSUE TITLE
ENHANCEMENT: CVX lab does not need the VTEP flood list CLI commands

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/atd-public#71]
Currently the CVX ATD lab uses the "vxlan" (option 24) jumphost script to execute configlets. Part of the "vxlan" configlets add a VTEP flood list which is not necessary when running CVX/VCS (because CVX assembles its own flood list).

This just confirms that perhaps the CVX lab needs it's own jumphost option called "cvx". This is tightly coupled to issue #70

**Comment by bingbucks** [comment]
I recently did an ATD and used this CVX ATD lab to demo MSS for a customer.

**Comment by bingbucks** [comment]
Assign to me

**Comment by bingbucks** [comment]
So, instead of creating another menu option in MenuOptions.yaml (which would then require changes to ConfigureTopology.py) I decided to remove the manual VTEP flood list as part of the lab as steps that the student must execute in the CLIs. This simplifies the code changes but also reinforces to the student (whom probably just did the VxLAN ATD lab) that with CVX you no longer need to manually enter a VTEP flood list.

**Comment by networkRob** [comment]
Fixed in #75
