### ISSUE TITLE
"LeafX-cvx01-Controller" configlets need to use Loopback1 not Loopback0

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/atd-public#72]
While this configlet does not seem to be invoke by MenuOption.yaml, it appears that its intention was for the CVX ATD lab. That being said the loopback 1 addresses should be used for the shared vVTEP addresses (172.16.0.34 & 172.16.0.56) in the ``vxlan source-interface Loopback0`` CLI config and instead should be ``vxlan source-interface Loopback1``.

While this configlet doesn't seem to be in use at the moment, use of it in the future will dictate Loopback 1 shared addresses.

**Comment by bingbucks** [comment]
Assign to me.

**Comment by networkRob** [comment]
Fixed in #75
