### ISSUE TITLE
Add "enable" (or allow privileged login) to ATD labs for Host1 & Host2

### ISSUE THREAD

**Issue by bingbucks** [aristanetworks/atd-public#74]
There are a few labs that need this update. When you log into Host1 or Host2, you are usually greeted with non-privileged mode. Either we update the ATD lab guides or we allow a login to the "#" prompt and not ">"... @networkRob Just a user config issue for the login credentials? Might be an enhancement tied to #35 

******
From Robert Welch (original request)
Team,

On PDF page 12, need to add the enable command before ping.

6. Log into Host 1 and Host 2, ping the gateway and the other host.

1. Host 1
enable
ping 172.16.112.1
ping 172.16.112.202
!! Note the MAC address returned by the command below:
show interface po1 | grep Hardware

3. Host 2
enable
ping 172.16.112.1
ping 172.16.112.201
!! Note the MAC address returned by the command below:
show interface po1 | grep Hardware

**Comment by networkRob** [comment]
Closing this issue since it has been addressed in the `datacenter-latest` topology.
