### ISSUE TITLE
Update CVP Labguides for Grant release

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#82]
Need to go through and update the labguides with screenshots and any workflow changes that have been updated in the Grant release.  

Any work on this should be put into the `grant-rel` branch.

**Comment by coreyhines** [comment]
<img width="2461" alt="Screen Shot 2019-12-09 at 2 29 13 PM" src="https://user-images.githubusercontent.com/8289837/70472553-e2c0f580-1a94-11ea-824b-c049afe96816.png">

**Comment by networkRob** [comment]
Fixed in #87
