### ISSUE TITLE
Update Labguides for new Cli Syntax

### ISSUE THREAD

**Issue by networkRob** [aristanetworks/atd-public#84]
In the `grant-rel` branch, please review the labguides in `topologies/datacenter-latest` directory.  There are references in the labguides to the older syntax style and they need to be updated.  The `datacenter-latest` topology will leverage 4.23.X release train.

**Comment by coreyhines** [comment]
I commited to the branch, should I close this issue, or leave it open until reviewed?

**Comment by networkRob** [comment]
Let's leave it open, we will reference this in the PR for Grant.

**Comment by networkRob** [comment]
Looks like the MLAG labguides need to be updated for the new CLI syntax.  Example of what I found is below.
Currently shows: 
```
no spanning-tree vlan 4094
```

Update to:
```
no spanning-tree vlan-id 4094
```
