### ISSUE TITLE
host2 did not get config for MLAG Lab

### ISSUE THREAD

**Issue by DimitriCapetz** [aristanetworks/atd-public#95]
When I ran the MLAG portion of the ATD lab, it did not configure the host2 uplink ports to the leaf3 and leaf4.  I did not see a configlet for it in CVP.  It's been a while since I've done a datacenter ATD (lots of routing ones :) ) but I thought that used to be applied automatically.  I didn't see anything in the guide instructing me to configure host2, just test it.

**Comment by networkRob** [comment]
@DimitriCapetz Good catch! I'll get the configlets created for both host devices and apply where necessary.

**Comment by DimitriCapetz** [comment]
branch patch-host-cfgs fixes this issue, per Rob's kickass work
